### ISSUE TITLE
CJK Extension H characters are not a character.

### ISSUE THREAD

**Issue by lxw618** [Ryosuke839/UnicodePad#105]
CJK Extension H characters have no UTF-8 and name at the information page.
![IMG_20221018_093400](https://user-images.githubusercontent.com/11721267/196314755-d582e668-e536-486f-a970-a026f62aaf01.jpg)

**Comment by Ryosuke839** [comment]
Thanks for reporting! This bug will be fixed in a release 2.12.0.
