### ISSUE TITLE
TangutSupp and SPUA characters can't be displayed correctly

### ISSUE THREAD

**Issue by onichan0923** [Ryosuke839/UnicodePad#118]
Characters in Tangut Supplement and Supplementary Private Use Area are displayed as masu symbol (〼) in the sheet, even if the font supports them, while they can be displayed correctly in the input box.
![Screenshot_2023-02-04-13-32-22-37_c6d2f5838c1fca5283099d09ba458d93](https://user-images.githubusercontent.com/68043613/216750802-42f501ba-110b-4f21-8019-ae491913def9.jpg)

![Screenshot_2023-02-04-13-36-11-88_c6d2f5838c1fca5283099d09ba458d93](https://user-images.githubusercontent.com/68043613/216750796-fbd3c9a0-5813-4c8b-9ee3-8b8e642645a0.jpg)

**Comment by Ryosuke839** [comment]
Thanks for the report! There was wrong data for codepoints not included in NamesList.txt. This will be addressed in #131.

**Comment by onichan0923** [comment]
comfirmed
