### ISSUE TITLE
The direction of U+1C90 Georgian Extended and U+1CC0 Sundanese Supplement seems to be reversed.

### ISSUE THREAD

**Issue by ungtl** [Ryosuke839/UnicodePad#126]
In a Chinese environment, the direction of U+1C90 Georgian Extended and U+1CC0 Sundanese Supplement seems to be reversed. I wonder if it is reversed in other environments.

**Comment by Ryosuke839** [comment]
Thanks for the report! This was a bug in code. This will be addressed in https://github.com/Ryosuke839/UnicodePad/pull/130.
