### ISSUE TITLE
Submit UnicodePad to F-Droid

### ISSUE THREAD

**Issue by Symbian9** [Ryosuke839/UnicodePad#17]
Pleade, submit UnicodePad for inclusion to F-Droid repo

- https://f-droid.org/en/contribute/
- https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

P.S.: Currently there is only one similar app on F-Droid

- https://f-droid.org/en/packages/org.madore.android.unicodeMap/

**Comment by IzzySoft** [comment]
Supporting this request, and assuming your approval (why not?), I've just [opened a request-for-packaging](https://gitlab.com/fdroid/rfp/issues/623). Meanwhile, your app is [listed with my repo](https://apt.izzysoft.de/fdroid/index/apk/jp.ddo.hotmist.unicodepad), which I hope you don't mind.

**Comment by PanderMusubi** [comment]
@Ryosuke839 Do you support the packaging of this app by F-Droid?

**Comment by IzzySoft** [comment]
**ping** @Ryosuke839 any opinion on this? As you haven't yet answered, I assume you're not opposed at least.

**Comment by Symbian9** [comment]
I close this issue as UnicodePad already on F-Droid.

**Comment by licaon-kter** [comment]
F-Droid can't build anymore since `com.google.android.gms:play-services-ads(-lite)` are not open-source.
