### ISSUE TITLE
The pop-up window below does not display the Unicode code point.

### ISSUE THREAD

**Issue by lxgw** [Ryosuke839/UnicodePad#187]
![Screenshot_20240919063555.jpg](https://github.com/user-attachments/assets/abf749a7-4818-4ef0-9e1e-2645f13c686f)

Older versions can display the Unicode code point on the caption of the center pop-up window.

![IMG_20240919_064645.png](https://github.com/user-attachments/assets/42405a87-2cf9-46f1-bbbc-3a6176e46f3a)

**Comment by ChiefMikeK** [comment]
Was fixed in latest reliese, @lxgw you can close this now 🥶
