### ISSUE TITLE
Missing tabs in v2.14.x

### ISSUE THREAD

**Issue by rxoom** [Ryosuke839/UnicodePad#190]
Tabs have been missing for me since v2.14.1
(Pixel 6, Android 14)

Importing settings, clean install, setting/resetting of the tab settings, no improvement. Tabs return with downgrade to v2.13.x

(The tutorial identifies the location of the tabs as if they were in the upper-left corner.)
![UnicodePad-tabs-missing](https://github.com/user-attachments/assets/7a277595-b4f4-4ede-9e12-801523b51a0b)

**Comment by Ryosuke839** [comment]
Hi there.

It should have been fixed by e2e4438d823c116eebdbec1372e33cf19e6edeb4, which is included in v2.14.3. Would you update to v2.14.3 and check again?

**Comment by rxoom** [comment]
Yes, thank you, the issue is fixed.
