### ISSUE TITLE
Add a way to copy the Unicode code point

### ISSUE THREAD

**Issue by PhilC813** [Ryosuke839/UnicodePad#195]
Due to how the current character detail pop-up menu is designed, with the Unicode code point only appearing as the title of the character tabs, there is no way to copy the code to the clipboard. 

The code point is a vital information and having a shortcut to copy it would be helpful, and reduce the odds of a typo if you have to transcribe it.

I'm not sure what the best way to add this capability would be, but the most simple one would be to add the code again in the character details section (name, UTF-8, Unicode version, etc.) as this area allows for the text to be selected and copied.

**Comment by ChiefMikeK** [comment]
@Ryosuke839 a question?

![Screenshot_20241201unicodepad](https://github.com/user-attachments/assets/18a06820-c7be-4f6a-8787-8ebc6042703b)

**Comment by Ryosuke839** [comment]
I guess I can go with the solution @PhilC813 mentioned.

https://github.com/Ryosuke839/UnicodePad/pull/196

**Comment by PhilC813** [comment]
Thank you!! Really appreciate it.

It could also have been placed below the character's name, in the same area with the UTF-8 code; text is selectable there as well. I'm just worried that if it's added as a prefix to the character name, that it may not play well on devices with narrow screens.
