### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by 532910** [Ryosuke839/UnicodePad#22]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
https://material.io/guidelines/style/icons.html

**Comment by Liggliluff** [comment]
This has been implemented, so this issue can be closed now.

**Comment by 532910** [comment]
2.5.0 not adaptive. In what version?

**Comment by Liggliluff** [comment]
My bad, it isn't adaptive. It's just Nova Launcher that cleverly made it into an adaptive icon.

Most non-adaptive icons that are turned pseudo-adaptive have the original icon small inside it, but the UnicodePad icon was large like a normal adaptive icon. I don't know why it's so similar to an adaptive icon when other non-adaptive icons aren't.
