### ISSUE TITLE
Support Unicode 12.0

### ISSUE THREAD

**Issue by ChiefMikeK** [Ryosuke839/UnicodePad#27]
# Version 12.0 of the Unicode Standard is now available,
 including the core specification, annexes, and data files. This version adds 554 characters, for a total of 137,929 characters.
- Mar 05, 2019 [Announcing The Unicode® Standard, Version 12.0](http://blog.unicode.org/2019/03/announcing-unicode-standard-version-120.html)
- Feb 05, 2019 [The Unicode Blog: Unicode Emoji 12.0 — final for 2019](http://blog.unicode.org/2019/02/unicode-emoji-12-final-for-2019.html)
## Fonts; _Since "Noto-Fonts" have not been updated for last couple of Unicode versions!_
- [Releases · googlei18n/noto-fonts](https://github.com/googlei18n/noto-fonts/releases)

- **Symbola** v.12.00; March 2019 includes latest characters from Unicode 12 _(font contains text presentation only for emoji characters/they are not colored)_!
--  [Unicode Fonts for Ancient Scripts](http://users.teilar.gr/~g1951d/)

![Symbola_12](file:///storage/emulated/0/MyDocs/md/Symbola_10.png)
![Symbola chessboard sampling](Symbola_chessboard.png)
----
### [CLDR; Other Subdivision Names: _United States_](https://www.unicode.org/cldr/charts/34/subdivisionNames/other.html#usak)
- [**BabelStone Flags** v. 2.07 is a font that supports multicolour flag glyphs for Unicode character sequences representing various national, sub-national, supra-national, and miscellaneous flags](http://www.babelstone.co.uk/Fonts/Flags.html)
![ColourFlagGlyphs](ColourFlagGlyphs.png)

**Comment by Ryosuke839** [comment]
Supported in release [v2.5.0](https://github.com/Ryosuke839/UnicodePad/releases/tag/v2.5.0)
