### ISSUE TITLE
How to set custom fonts for UnicodePad on non-rooted devices?

### ISSUE THREAD

**Issue by Symbian9** [Ryosuke839/UnicodePad#32]
Give instruction on installing and setting custom fonts for UnicodePad.

Would UnicodePad recognize fonts (`.ttf`/`.otf` files) placed in `/sdcard/.fonts/` folder?

**Comment by ChiefMikeK** [comment]
On my Samsung running Android 6.0.1 unrooted
*  /storage/emulated/0/fonts 《without leaving dot or capitalized》
*  /sdcard/fonts
*  /system/fonts

work just fine but not the external sdcard due to android storage framework :neckbeard:

**Comment by Symbian9** [comment]
> On my Samsung running Android 6.0.1 unrooted
>
> - `/storage/emulated/0/fonts` (without leaving 'dot' or capitalized)
> - `/sdcard/fonts`
> - `/system/fonts`

Well, if custom fonts would be installes, how choose font in *UnicodePad*?

**Comment by Liggliluff** [comment]
Open the app; find the option for font, where it should say it's system default. Press that and select the option to choose. You'll then be able to locate the file.

You don't have to put the fonts in a fonts folder. But it certainly helps to find them.
