### ISSUE TITLE
Broken Light theme in 2.6.0

### ISSUE THREAD

**Issue by Rikk** [Ryosuke839/UnicodePad#38]
Other than the increased sizes (apk and system generated dalvik-cache), and the addition of ads (something users dislike, but thankfully with an option to disable), new version also has problems with Light theme:

![UnicodePad 2 6 0 - Broken Light theme](https://user-images.githubusercontent.com/2916485/77247510-bb8bcf80-6c10-11ea-8e33-6837adadb9e4.png)

**Comment by Ryosuke839** [comment]
This seems to be caused by wrong order of AppCompatActivity method calls.

3df90d21d738e4dafe57d40859a3003cf6a6b087 should solve this issue.
