### ISSUE TITLE
Use Storage Access Framework to choose a font

### ISSUE THREAD

**Issue by Ryosuke839** [Ryosuke839/UnicodePad#46]
From Android 4.4 (API 19), Storage Access Framework can be used to select a file.

**Comment by ChiefMikeK** [comment]
## FAQ suggestion
### Q: How can I use a custom font in an android.apk app?   
- A.
1. First create new directory in your user's root folder
2. Should be __all-lower-case__ `/storage/emulated/0/fonts
` 
3. Download a `*.ttf` or `*.otf` file and move it the `/fonts` directory.
4. From **UnicodePad** click on the `Font` **Default** `Select...` pulldown and select your custom font
-  Note: Fonts are displayed in pulldown by selection order and not alphabetical order!  

![Image](https://github.com/ChiefMikeK/feedback/raw/master/img/MyFontsDirectory.png)
### Q: Where can I find a font that supports the latest Unicode® Version?
- A. Just do a search on [Github](https://github.com/topics/font?o=desc&s=updated) look for recently updated fonts that are tagged Unicode 👍
