### ISSUE TITLE
F-Droid can't build anymore since `com.google.android.gms:play-services-ads(-lite)` are not open-source.

### ISSUE THREAD

**Issue by lfourquaux** [Ryosuke839/UnicodePad#48]
F-Droid can't build anymore since `com.google.android.gms:play-services-ads(-lite)` are not open-source.

_Originally posted by @licaon-kter in https://github.com/Ryosuke839/UnicodePad/issues/17#issuecomment-605900019_

The F-Droid version is increasingly outdated, it would be nice to have a fully open source, up to date version of UnicodePad.

**Comment by TPS** [comment]
@Ryosuke839 What's needed is a _flavor_ to include only what's acceptable to build for F-droid.

@licaon-kter, @Izzysoft:  Any pointers on how to do such would be much appreciated. 🙇🏾‍♂️

**Comment by IzzySoft** [comment]
I'm neither dev nor packager – so the only advice I can give is check with other apps which have done that (setting up separate flavors). In our `*.yml` files you can tell them by using gradle with a specific name, e.g.

```yaml
gradle:
  - foss
```

`foss` and `fdroid` are quite common with those, so a `egrep '^\s*- (fdroid|foss)' *.yml` should help identifying them.

**Comment by t-8ch** [comment]
@Ryosuke839 Would you accept a pullrequest for such a build variant?

**Comment by Ryosuke839** [comment]
@t-8ch Yes! I will definitely accept on this repo once I validate the behavior.

**Comment by TPS** [comment]
@Ryosuke839 Maybe check https://github.com/t-8ch/UnicodePad/pull/1 so you can do so _before_ PR here?

**Comment by t-8ch** [comment]
@Ryosuke839 Thanks!
@TPS Welp, I managed to mess up the PR, it should against the repo of @Ryosuke839 obviously :-)

**Comment by TPS** [comment]
@t-8ch You mentioned a problem in your PR, anyway.  Probably better to fix there than PR _here_ until it's resolved?

**Comment by t-8ch** [comment]
@TPS it's more of a validation issue. I expect it to actually work, but for some reason the Ads are not shown at all for me, even in the origin version.
If any changes are necessary I can do those in this PR easily.

**Comment by TPS** [comment]
@IzzySoft Now that #74 is merged, is anything else needed to have F-Droid start publishing this again?

**Comment by t-8ch** [comment]
I think the timeline would be:
* Wait for a new release of UnicodePad (I would just for the one containing Unicode 14)
* Update the fdroid definitions to activate the "fdroid" flavor

**Comment by linsui** [comment]
2.9.1 will be published soon. See https://monitor.f-droid.org/builds/running. When the next release available please open an MR the update the build recipe.
