### ISSUE TITLE
The list of characters at the find tab might be larger than the screen

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [Ryosuke839/UnicodePad#55]
It seems as if the list of characters at the find tab was larger than the screen. 

It looks like this when I scroll to the end of the list: 
![Screenshot_20200818-164559](https://user-images.githubusercontent.com/43148954/90527984-6a0d4f80-e172-11ea-8b22-a0b02b1c10e7.png)

Compare the scroll bar lengths: 
![Screenshot_20200818-164951](https://user-images.githubusercontent.com/43148954/90528430-e6a02e00-e172-11ea-9a0c-fecb8936b8e2.png)

**Comment by Ryosuke839** [comment]
Have you set "UI scroll" setting "Always"?

Try setting it "Never" or "Only in landscape".

**Comment by M-A-R-T-I-N-1** [comment]
That works, sorry for bothering you. 
May you consider making "never" a default value? 
It's sometimes damn difficult to scroll to the desired position. (E.g. one in the ten scroll attempts works.)
