### ISSUE TITLE
Support Unicode 11.0

### ISSUE THREAD

**Issue by Ryosuke839** [Ryosuke839/UnicodePad#9]
Unicode 11.0 will be released in June 2018.

**Comment by Symbian9** [comment]
Unicode 11.0 released!

- http://blog.unicode.org/2018/06/announcing-unicode-standard-version-110.html

Now there is "COPYLEFT SYMBOL"! ;-)

> 1F12F 🄯 COPYLEFT SYMBOL
> ![COPYLEFT SYMBOL](https://i.imgur.com/NOfBvNg.png)

**Comment by Ryosuke839** [comment]
I'm working on it.
Wait for a while!

**Comment by Ryosuke839** [comment]
Supported Unicode 11.0 in #14 and this is included in v2.4.0 (71656fb)
